name: Feature request
description: Suggest an idea or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion! Please include context about your GitLab setup (without secrets).

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: "It is currently hard to ..."
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to happen?
      placeholder: "Add/Change ..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternatives you considered?
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Screenshots, links, constraints, etc. (redact secrets).
    validations:
      required: false
